export const COUNTRIES = [
  "Bangladesh",
  "USA",
  "Germany",
  "France",
  "Spain",
  "Brazil",
  "Italy",
  "Netherlands",
  "Poland",
  "India",
  "Canada",
  "Mexico",
  "Japan",
  "South Korea",
  "Australia",
  "Russia",
  "Turkey",
  "Saudi Arabia",
  "South Africa",
  "Nigeria",
  "Egypt",
  "Argentina",
  "Colombia",
  "Vietnam",
  "Thailand",
] as const;

export const LOCALES = [
  "bn_BD",
  "en_US",
  "de_DE",
  "fr_FR",
  "es_ES",
  "pt_BR",
  "it_IT",
  "nl_NL",
  "pl_PL",
  "hi_IN",
  "en_CA",
  "es_MX",
  "ja_JP",
  "ko_KR",
  "en_AU",
  "ru_RU",
  "tr_TR",
  "ar_SA",
  "en_GB",
  "en_NG",
  "ar_EG",
  "es_AR",
  "es_CO",
  "vi_VN",
  "th_TH",
  "en_IN",
] as const;

// -------------------------------------------------------------------
// Helper: get display name for locale
// -------------------------------------------------------------------
export const LOCAL_NAMES: Record<string, string> = {
  bn_BD: "Bengali (Bangladesh)",
  en_US: "English (US)",
  de_DE: "German",
  fr_FR: "French",
  es_ES: "Spanish (Spain)",
  pt_BR: "Portuguese (Brazil)",
  it_IT: "Italian",
  nl_NL: "Dutch",
  pl_PL: "Polish",
  hi_IN: "Hindi",
  ja_JP: "Japanese",
  ko_KR: "Korean",
  ru_RU: "Russian",
  ar_SA: "Arabic (Saudi Arabia)",
  tr_TR: "Turkish",
  en_CA: "English (Canada)",
  es_MX: "Spanish (Mexico)",
  en_AU: "English (Australia)",
  en_GB: "English (Great Britain)",
  en_NG: "English (Nigeria)",
  ar_EG: "Arabic (Egypt)",
  es_AR: "Spanish (Argentina)",
  es_CO: "Spanish (Colombia)",
  vi_VN: "Vietnamese",
  th_TH: "Thai",
  en_IN: "English (India)",
};


// -------------------------------------------------------------------
// Country to allowed locales (always includes English)
// -------------------------------------------------------------------
export const COUNTRY_LOCALES: Record<string, string[]> = {
  Bangladesh: ["bn_BD", "en_US"],
  USA: ["en_US"],
  Germany: ["de_DE", "en_US"],
  France: ["fr_FR", "en_US"],
  Spain: ["es_ES", "en_US"],
  Brazil: ["pt_BR", "en_US"],
  Italy: ["it_IT", "en_US"],
  Netherlands: ["nl_NL", "en_US"],
  Poland: ["pl_PL", "en_US"],
  India: ["hi_IN", "en_US"],
  Canada: ["en_CA", "en_US"],
  Mexico: ["es_MX", "en_US"],
  Japan: ["ja_JP", "en_US"],
  "South Korea": ["ko_KR", "en_US"],
  Australia: ["en_AU", "en_US"],
  Russia: ["ru_RU", "en_US"],
  Turkey: ["tr_TR", "en_US"],
  "Saudi Arabia": ["ar_SA", "en_US"],
  "South Africa": ["en_US"],
  Nigeria: ["en_NG", "en_US"],
  Egypt: ["ar_EG", "en_US"],
  Argentina: ["es_AR", "en_US"],
  Colombia: ["es_CO", "en_US"],
  Vietnam: ["vi_VN", "en_US"],
  Thailand: ["th_TH", "en_US"],
};